In [6]:

import pandas as pd
Spotify_data =  pd.read_csv("C:\\Users\\medin\\Downloads\\Most Streamed Spotify Songs 2024.csv", header=0, encoding='latin1')
Spotify_data
Spotify_data.head()

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,QM24S2402528,1,725.4,"390,470,936","30,716","196,631,588",...,684,62.0,"17,598,718",114.0,"18,004,655","22,931","4,818,457","2,669,262",NaN,0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,USUG12400910,2,545.9,"323,703,884","28,113","174,597,137",...,3,67.0,"10,422,430",111.0,"7,780,028","28,444","6,623,075","1,118,279",NaN,1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,QZJ842400387,3,538.4,"601,309,283","54,331","211,607,669",...,536,136.0,"36,321,847",172.0,"5,022,621","5,639","7,208,651","5,285,340",NaN,0
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,USSM12209777,4,444.9,"2,031,280,633","269,802","136,569,078",...,"2,182",264.0,"24,684,248",210.0,"190,260,277","203,384",NaN,"11,822,942",NaN,0
4,Houdini,Houdini,Eminem,5/31/2024,USUG12403398,5,423.3,"107,034,922","7,223","151,469,874",...,1,82.0,"17,660,624",105.0,"4,493,884","7,006","207,179","457,017",NaN,1

In [11]:
top_songs = Spotify_data.sort_values(by='Spotify Streams', ascending=False).head(10)
top_songs

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
3157,Best Day Of My Life,American Authors - EP,American Authors,1/1/2013,USUM71302187,"3,140",24.6,"999,525,686","147,511","76,137,901",...,541,55.0,"143,084",35.0,"595,709,385","333,439",NaN,"8,366,702",NaN,0
137,vampire,vampire,Olivia Rodrigo,6/30/2023,USUG12304091,138,128.9,"998,964,097","90,793","87,801,398",...,93,61.0,"5,239,925",128.0,"28,318,435","67,590","4,296,515","4,872,257",NaN,1
44,My Love Mine All Mine,The Land Is Inhospitable and So Are We,Mitski,9/15/2023,USJ5G2335007,45,206.2,"997,702,304","105,927","92,834,002",...,"2,676",63.0,"10,874,749",110.0,"6,151,267","9,160","7,980,051","2,682,219",NaN,0
785,vampire,vampire,Olivia Rodrigo,6/30/2023,USUG12305004,781,54.8,"997,536,616","5,268","1,949,130",...,NaN,2.0,"18,375",2.0,NaN,NaN,NaN,NaN,NaN,0
1179,Wake Up in the Sky,Wake Up in the Sky,Gucci Mane,9/14/2018,USAT21811087,"1,173",43.8,"996,942,947","188,378","27,325,666",...,56,31.0,"108,234",17.0,"165,992,311","128,939",NaN,"6,648,622",NaN,1
2395,Benjamins Deli,Benjamins Deli - Single,JRitt,10/24/2023,QZTBA2358000,"2,389",29.2,"996,881",446,"255,703",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3508,I Was Never There,"My Dear Melancholy,",The Weeknd,3/29/2018,USUG11800570,"3,488",23.1,"995,463,505","139,596","44,549,966",...,NaN,20.0,"255,988",NaN,"18,564,718","7,254",NaN,"3,364,449",NaN,0
969,Piece Of Your Heart,Piece Of Your Heart,MEDUZA,2/1/2019,DEUM71807719,966,49.2,"995,452,298","188,608","44,047,615",...,196,166.0,"2,039,570",43.0,"46,973,428","14,833","26,135,531","14,464,887",NaN,0
1707,Vete,Vete,Bad Bunny,11/21/2019,QMFME1914637,"1,702",35.4,"991,885,224","101,177","25,041,872",...,83,40.0,"216,331",14.0,"126,271,911","38,291",NaN,"1,422,487",NaN,1
4446,Feel So Close - Radio Edit,Dance Hitlist 2012.1,Calvin Harris,1/1/2011,GBARL1100748,"4,411",19.9,"991,382,346","187,432","87,928,081",...,NaN,84.0,"942,311",29.0,"426,156,682","480,102",NaN,"7,721,049",NaN,0